game_size: 6
n_rounds: 500

models: 
  - "crsa"
  - "crsa_wm" 
  - "yrsa" 
  - "yrsa_wm" 
  - "yrsa-literal" 
  - "yrsa-literal_wm" 
  - "crsa-literal"
  - "crsa-literal_wm"
  - "prior"

alpha: 2.5
tolerance: 1e-3
max_depth: inf
seed: 7423
log_every_n_turns: 10