
meanings: ["David Lewis", "Paul Grice", "Claude Shannon"]

utterances: ["beard", "glasses", "tie"]

lexicon: [
  [1, 0, 0],
  [1, 1, 0],
  [0, 1, 1]
]

prior: null

cost: null

alphas: [1.0, 1.0, 1]

depths: [3, [10, 20, 30], 10]

