
dialog: ["1st", "2nd", "2nd", "2nd"]
dialog_meaning_A: "AAA"
dialog_meaning_B: "212"
dialog_target: "2nd"

meanings_A: ["AAA", "AAB", "ABA", "ABB", "BAA", "BAB", "BBA", "BBB"]
meanings_B: ["111", "112", "121", "122", "211", "212", "221", "222"]
categories: ["None", "1st", "2nd", "3rd"]

prior: [
    [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]],
    [[0, 0, 0, 0], [0, 0, 0, 0], [0, 1, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 1, 0], [1, 0, 0, 0], [1, 0, 0, 0]],
    [[0, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1], [1, 0, 0, 0], [0, 0, 0, 1], [1, 0, 0, 0]],
    [[0, 1, 0, 0], [0, 1, 0, 0], [0, 1, 0, 0], [0, 1, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0]],
    [[0, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0], [0, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]],
    [[0, 0, 1, 0], [0, 0, 1, 0], [1, 0, 0, 0], [1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 1, 0], [1, 0, 0, 0], [1, 0, 0, 0]],
    [[0, 0, 0, 1], [1, 0, 0, 0], [0, 0, 0, 1], [1, 0, 0, 0], [0, 0, 0, 1], [1, 0, 0, 0], [0, 0, 0, 1], [1, 0, 0, 0]],
    [[1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0]],
]

utterances: ["1st", "2nd", "3rd"]

lexicon_A: [
    [1, 1, 1, 1, 0, 0, 0, 1],
    [1, 1, 0, 0, 1, 1, 0, 1],
    [1, 0, 1, 0, 1, 0, 1, 1],
]
lexicon_B: [
    [1, 1, 1, 1, 0, 0, 0, 1],
    [1, 1, 0, 0, 1, 1, 0, 1],
    [1, 0, 1, 0, 1, 0, 1, 1],
]

alphas: [0.1, 1.0, 2.5]
max_depths: [null, null, null]
tolerances: [0.001, 0.001, 0.001]
seed: 7384