
meanings_A: ["AA", "AB", "BA", "BB"]
meanings_B: ["11", "12", "21", "22"]
categories: ["None", "1st", "2nd"]

prior: [
    [[0, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0]],
    [[0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]],
    [[0, 0, 1], [1, 0, 0], [0, 0, 1], [1, 0, 0]],
    [[1, 0, 0], [1, 0, 0], [1, 0, 0], [1, 0, 0]],
]

utterances_A: ["1st", "2nd"]
utterances_B: ["1st", "2nd"]

cost_A: null
cost_B: null

lexicon_A: [
    [1, 1, 0, 1],
    [1, 0, 1, 1],
]
lexicon_B: [
    [1, 1, 0, 1],
    [1, 0, 1, 1],
]
