
meanings: ['Lover', 'Friend', 'Somebody', 'Unfriend', 'Hater']
utterances: ['I love you', 'I like you', 'You make me indifferent', 'I dislike you', 'I hate you']

lexicon: [
  [1, 1, 0, 0, 1],
  [1, 1, 0, 0, 0],
  [1, 0, 1, 1, 1],
  [1, 0, 0, 1, 1],
  [1, 1, 0, 0, 1]
]
prior: [0.2, 0.2, 0.2, 0.2, 0.2]
cost: [0.0, 0.0, 0.0, 0.0, 0.0]

